name: Lint Workflow Templates

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint-workflow-templates:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout latest changes from the PR branch
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4 

      - name: Set up Kind cluster with Helm
        uses: helm/kind-action@v1.6.0
        with:
          cluster_name: argo-lint-cluster

      # - name: Install Argo CLI
      #   run: |
      #     gunzip argo-linux-amd64.gz
      #     chmod +x argo-linux-amd64
      #     sudo mv argo-linux-amd64 /usr/local/bin/argo
      #     argo version

      - name: Install Argo
        run: |
          helm repo add argo https://argoproj.github.io/argo-helm
          helm repo update
          kubectl create namespace argo
          helm install argo argo/argo-workflows --namespace argo

      - name: Install Argo CLI
        run: |
          gunzip argo-linux-amd64.gz
          chmod +x argo-linux-amd64
          sudo mv argo-linux-amd64 /usr/local/bin/argo
          argo version
          
      - name: Argo Lint Workflow Template
        run: |
          # Path to your Argo Workflow Template YAML file
          for file in workflows/argo-events/workflowtemplates/*.yaml; do
              echo "Linting workflow template: $file"
              argo lint $file
          done
